import 'dart:math';

/// Biscuits chinois : drôle sans être lourd, identifiant (« ah oui »), philosophique et citations.
class FortuneCookieService {
  FortuneCookieService._();

  static final _random = Random();

  static const List<String> _fortunes = [
    // ——— Identification (« ah oui, c’est moi ») ———
    "Vous reportez souvent les choses au lendemain. Aujourd'hui, vous avez ouvert ce biscuit. C'est déjà ça.",
    "Parfois vous avez l'impression de courir sans avancer. Vous avancez quand même.",
    "Vous êtes du genre à tout prendre à cœur. Rappelez-vous : tout n'est pas de votre faute.",
    "Vous attendez souvent le bon moment. Parfois le bon moment, c'est maintenant.",
    "Vous vous demandez si vous en faites assez. Vous en faites. Plus que vous ne croyez.",
    "Vous êtes plus courageux que vous ne le croyez. La preuve : vous êtes encore là.",
    "Vous avez déjà surmonté des choses que vous pensiez insurmontables. Vous pouvez encore.",
    "Parfois la meilleure décision est de ne pas décider tout de suite. Et c'est ok.",
    "Vous avez besoin de pauses. Les prendre n'est pas de la paresse, c'est du respect.",
    "Vous comparez souvent votre parcours à celui des autres. Le vôtre vous suffit.",
    "Vous ruminez parfois avant de dormir. Ce soir, respirez. Demain sera un autre jour.",
    "Vous donnez beaucoup aux autres. N'oubliez pas de vous garder un peu pour vous.",
    "Vous avez peur de décevoir. La plupart du temps, vous vous imposez cette peur tout seul.",
    "Vous cherchez parfois une permission pour vous reposer. La voici : reposez-vous.",
    "Vous avez déjà vécu des « jamais je n'y arriverai ». Vous y êtes arrivé.",
    "Vous êtes plus résilient que votre tête ne veut bien le dire.",
    "Parfois vous vous en demandez trop. Aujourd'hui, une chose à la fois suffit.",
    "Vous avez le droit de ne pas être au top tous les jours. Personne ne l'est.",
    "Vous avez aidé quelqu'un sans le savoir. C'est souvent comme ça que ça marche.",
    "Vous avez besoin d'être rassuré de temps en temps. C'est humain. Voilà : ça va aller.",
    "Vous attendez parfois un signe. En ouvrant ce biscuit, vous en avez pris un. Bien joué.",
    "Vous vous jugez plus sévèrement que les autres ne vous jugent. Accordez-vous une trêve.",
    "Vous avez déjà fait des choix qui vous ont fait grandir. Vous en ferez d'autres.",
    "Parfois vous vous sentez à côté de la plaque. Vous êtes au bon endroit. Continuez.",
    "Vous méritez d'être fier de vous. Même des petites victoires. Surtout des petites.",
    "Vous avez le droit de changer d'avis. Ce n'est pas de l'indécision, c'est de l'honnêteté.",
    "Vous avez tendance à minimiser ce que vous accomplissez. Arrêtez. C'est déjà beaucoup.",
    "Vous avez besoin qu'on vous le dise : vous faites du bien autour de vous.",
    "Parfois vous vous sentez seul dans votre tête. Vous ne l'êtes pas. Beaucoup vous comprennent.",
    "Vous avez déjà traversé des moments difficiles. Vous êtes encore debout. Ça compte.",
    "Vous attendez parfois une validation extérieure. La vôtre compte autant.",
    "Vous êtes du genre à anticiper le pire. Parfois le pire n'arrive pas. Soufflez.",
    "Vous avez le droit de ne pas tout savoir. Personne ne sait tout.",
    "Vous vous souciez des autres. Quelqu'un se soucie de vous aussi. Même si vous ne le voyez pas.",
    "Vous avez besoin d'entendre que vous êtes sur la bonne voie. Vous l'êtes.",
    "Parfois vous vous sentez dépassé. C'est normal. Demain sera un peu plus clair.",
    "Vous avez déjà fait des choses que vous n'auriez jamais cru pouvoir faire. Vous pouvez encore.",
    "Vous méritez de la douceur. Commencez par vous en offrir.",
    "Vous avez le droit de dire non. Sans vous justifier pendant une heure.",
    "Vous avez tendance à tout rationaliser. Parfois, ressentir suffit.",
    "Vous avez besoin de légèreté. Ce biscuit en est une. Prenez-en d'autres.",
    "Vous vous demandez si vous êtes « assez ». Vous êtes assez. Point.",
    "Parfois vous avez l'impression de répéter les mêmes erreurs. Vous apprenez à chaque fois.",
    "Vous avez déjà fait sourire quelqu'un aujourd'hui. Ou vous allez le faire. Les deux comptent.",
    "Vous avez le droit de ne pas avoir de réponse tout de suite. Le flou fait partie du chemin.",
    "Vous êtes plus aimé que vous ne le pensez. Même quand vous ne le voyez pas.",
    "Vous avez besoin qu'on vous rappelle que vous comptez. Vous comptez.",
    "Parfois vous vous épuisez à vouloir tout bien faire. Assez bien, c'est déjà bien.",
    "Vous avez déjà choisi la bienveillance quand c'était difficile. Vous pouvez le refaire.",
    "Vous méritez un moment de calme. Prenez-le. Sans culpabilité.",
    "Vous avez le droit de ne pas être productif tous les jours. Les jours « off » comptent aussi.",
    "Vous avez parfois l'impression de ne pas être à la hauteur. Vous l'êtes. La hauteur, c'est vous qui la définissez.",
    "Vous vous excusez trop. Pour exister, pour demander, pour prendre de la place. Vous avez le droit d'être là.",
    "Vous avez besoin de temps seul pour recharger. Ce n'est pas de l'égoïsme, c'est de la survie.",
    "Vous avez déjà pardonné à quelqu'un. Un jour, vous pourrez vous pardonner à vous-même.",
    "Vous attendez que tout soit parfait pour commencer. Le mieux est souvent l'ennemi du bien. Commencez.",
    "Vous vous sentez parfois transparent. Vous ne l'êtes pas. Vous comptez pour quelqu'un.",
    "Vous avez le droit de ne pas savoir où vous allez. Le chemin se dessine en marchant.",
    "Vous donnez une deuxième chance aux autres. Offrez-vous-en une aussi.",
    "Vous avez tendance à tout garder pour vous. Parler, même à une personne, peut tout changer.",
    "Vous avez déjà été la bonne personne au bon moment. Sans le savoir. Merci.",
    "Vous vous réveillez parfois avec l'angoisse. Elle passe. Respirez. Ce biscuit est avec vous.",
    "Vous avez besoin d'être vu pour ce que vous faites. Ce que vous faites compte. Vous comptez.",
    "Vous avez le droit de poser des limites. Sans vous justifier. Non, c'est une phrase complète.",
    "Vous vous sentez parfois en décalage. Le décalage fait souvent les plus belles rencontres.",
    "Vous avez déjà fait preuve de courage sans le nommer. C'était du courage. Continuez.",
    "Vous avez besoin qu'on vous dise que vous pouvez faire une pause. Vous pouvez. Faites une pause.",
    "Vous vous inquiétez pour les autres. Quelqu'un s'inquiète pour vous. Pensez-y.",
    "Vous avez le droit de ne pas aimer certaines journées. Demain en sera une autre.",
    "Vous avez tendance à voir ce qui manque. Aujourd'hui, regardez aussi ce qui est là.",
    "Vous avez déjà inspiré quelqu'un. Ils ne vous l'ont peut-être pas dit. C'est vrai.",
    "Vous vous sentez parfois perdu. Être perdu fait partie du voyage. Vous retrouverez le nord.",
    "Vous avez besoin de douceur. Offrez-vous-en. Un biscuit. Un moment. Une respiration.",
    "Vous avez le droit de ne pas être d'accord. Avec les autres. Avec vous-même. Avec ce biscuit. (Non, avec ce biscuit, si.)",
    "Vous avez déjà surmonté un « je n'y arriverai jamais ». Vous y êtes arrivé. Vous pouvez encore.",
    "Vous vous mettez souvent en dernier. Aujourd'hui, mettez-vous au moins à égalité.",
    "Vous avez besoin de croire que ça va aller. Ça va aller. Pas toujours comme prévu. Mais ça va aller.",
    "Vous avez le droit de changer de direction. Ce n'est pas de l'échec, c'est de l'ajustement.",
    "Vous avez tendance à sous-estimer votre impact. Vous en avez un. Positif.",
    "Vous vous souvenez des erreurs plus que des réussites. Les deux font de vous qui vous êtes.",
    "Vous avez besoin d'un signe. En ouvrant ce biscuit, vous en avez pris un. Le voici.",
    "Vous avez le droit de ne pas tout expliquer. À personne. Pas même à vous-même.",
    "Vous avez déjà fait la différence. Vous la ferez encore. Sans toujours le voir.",
    "Vous vous sentez parfois en retard sur la vie. Il n'y a pas de bon rythme. Il y a le vôtre.",
    "Vous avez besoin de vous sentir légitime. Vous l'êtes. Vous n'avez pas à prouver quoi que ce soit.",
    "Vous avez le droit de pleurer. Ou de rire. Ou les deux. Les émotions ne sont pas des faiblesses.",
    "Vous avez tendance à tout prendre au sérieux. La légèreté aussi est un choix. Ce biscuit vous y invite.",
    "Vous vous demandez si vous êtes sur la bonne voie. Si vous vous posez la question, vous avancez. C'est déjà la bonne voie.",
    "Vous avez besoin d'entendre que vous êtes capable. Vous l'êtes. Ce biscuit vous le confirme.",
    "Vous avez le droit de refuser. Une invitation. Une charge. Un biscuit. (Enfin, refusez pas le biscuit.)",
    "Vous avez déjà été la lumière pour quelqu'un. Vous pouvez l'être encore. Pour vous aussi.",
    "Vous vous sentez parfois trop sensible. La sensibilité est une force. Elle vous connecte au monde.",
    "Vous avez besoin de temps pour digérer les choses. Prenez-le. Le temps n'est pas l'ennemi.",
    "Vous avez le droit de ne pas avoir de plan. Le plan se fait en marchant. Marchez.",
    "Vous avez tendance à vous oublier dans l'équation. Remettez-vous dedans. Vous comptez.",
    "Vous vous réveillez parfois sans énergie. Les jours sans comptent aussi. Reposez-vous.",
    "Vous avez besoin de savoir que vous n'êtes pas seul. Vous ne l'êtes pas. Beaucoup vous comprennent.",
    "Vous avez le droit de ne pas être constant. Personne ne l'est. Les hauts et les bas font la vie.",
    "Vous avez déjà choisi la gentillesse. Vous pouvez le refaire. La gentillesse n'est jamais perdue.",
    "Vous vous sentez parfois à côté. Vous êtes au bon endroit. Le « à côté » est souvent le centre.",
    "Vous avez besoin de croire en vous. Ce biscuit y croit. Nous aussi. Rejoignez-nous.",
    // ——— Philosophique / sagesse ———
    "Le chemin se fait en marchant.",
    "La sérénité n'est pas l'absence de tempête, c'est la paix au milieu.",
    "Ce qui compte n'est pas de ne jamais tomber, c'est de se relever.",
    "La simplicité est la sophistication suprême.",
    "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",
    "Le bonheur est parfois un détour qu'on n'avait pas prévu.",
    "Chaque jour est une page blanche. Vous en êtes l'auteur.",
    "La patience n'est pas d'attendre, c'est de garder le cap en attendant.",
    "Ce que vous cherchez est souvent plus proche que vous ne pensez.",
    "La vie est ce qui nous arrive pendant qu'on fait d'autres projets. Profitez de ce qui arrive.",
    "Le présent est le seul moment où vous pouvez agir. Le reste est souvenir ou fantasme.",
    "La sagesse commence par l'émerveillement.",
    "On ne peut pas contrôler le vent, mais on peut ajuster les voiles.",
    "La plus grande liberté est de ne plus avoir besoin d'avoir raison.",
    "Le calme n'est pas l'absence de bruit, c'est la paix en soi.",
    "Grandir, c'est accepter de ne pas tout maîtriser.",
    "La bienveillance envers soi est le premier pas vers les autres.",
    "Ce qui est simple est souvent le plus juste.",
    "La vraie force est de savoir demander de l'aide.",
    "Le doute fait partie du chemin. La certitude n'est pas une obligation.",
    "Chaque petit pas compte. Même ceux qu'on ne voit pas.",
    "La gratitude transforme ce qu'on a en assez.",
    "Le courage n'est pas l'absence de peur, c'est avancer avec.",
    "La paix intérieure se construit pas à pas, pas d'un coup.",
    "On ne change pas le passé. On peut changer le regard qu'on pose dessus.",
    "La légèreté est un choix. Parfois le plus difficile.",
    "Ce qui vous nourrit vraiment est rarement compliqué.",
    "La confiance se construit en agissant, pas en attendant.",
    "Le sens de la vie est souvent dans les petites choses.",
    "Accepter l'imperfection, c'est s'offrir la paix.",
    "La clarté vient en marchant, pas en restant immobile.",
    "Le bonheur n'est pas une destination, c'est une façon de voyager.",
    "La résilience, c'est repartir après avoir trébuché. Vous l'avez déjà fait.",
    "Ce qui semble insurmontable aujourd'hui sera un souvenir demain.",
    "La douceur envers soi n'est pas de la faiblesse.",
    "Le présent est le seul cadeau qu'on puisse vraiment ouvrir.",
    "La sagesse est de savoir qu'on ne sait pas tout.",
    "On ne peut pas tout contrôler. Et ce n'est pas grave.",
    "La joie se cultive. Comme un jardin. Petit à petit.",
    "Le sens naît souvent de ce qu'on donne, pas de ce qu'on accumule.",
    "La lenteur n'est pas un défaut quand elle mène à la justesse.",
    "Le repos fait partie du travail. Sans lui, rien ne tient.",
    "La vulnérabilité n'est pas l'opposé de la force. Elle en est parfois la source.",
    "Chaque fin est un commencement. Même quand on ne voit pas encore la suite.",
    "La joie n'a pas besoin de raison. Elle peut être là. Comme ça.",
    "Le pardon n'est pas pour les autres. C'est d'abord pour soi.",
    "La beauté est dans l'attention qu'on pose sur les choses.",
    "On ne peut pas tout prévoir. Et c'est souvent mieux ainsi.",
    "La parole juste au bon moment vaut plus que mille mots.",
    "Le mouvement apaise l'esprit. Marcher, respirer, agir.",
    "La peur indique souvent ce qui compte. Écoutez-la, puis avancez.",
    "Chaque rencontre peut changer quelque chose. Même une petite.",
    "Le détachement n'est pas l'indifférence. C'est la paix avec ce qu'on ne contrôle pas.",
    "La persévérance est une forme de courage. Vous en avez déjà fait preuve.",
    "Le sens de l'humour est une sagesse. Gardez-le.",
    "La nuit porte conseil. Le matin aussi. Et parfois un biscuit.",
    "On grandit en acceptant ce qu'on ne peut pas changer.",
    "La générosité revient. Pas toujours comme on l'attend. Mais elle revient.",
    "Le silence peut être une réponse. Une pause. Un respect.",
    "La confiance se mérite. Y compris en soi. Donnez-vous-en.",
    "Chaque effort compte. Même celui qu'on ne voit pas.",
    "La modestie n'est pas de se sous-estimer. C'est de rester ouvert.",
    "Le bonheur des autres nous rend plus heureux. La bienveillance est circulaire.",
    "La clarté vient souvent après l'action. Agir éclaire.",
    "On ne perd pas son temps quand on se repose. On le réinvestit.",
    "La vérité n'est pas toujours confortable. Elle libère.",
    "Le lien avec les autres nous tient debout. Cultivez-le.",
    "La créativité est en chacun. Elle demande juste d'être invitée.",
    "Chaque jour offre une nouvelle chance. Pas de repartir de zéro. De repartir.",
    "La douceur avec soi permet la douceur avec les autres.",
    "Le passé nous construit. Il ne nous définit pas.",
    "La curiosité garde le cœur jeune. Restez curieux.",
    "On ne peut pas plaire à tout le monde. Plaire à soi est déjà beaucoup.",
    "La gratitude allège. Ce qu'on a pèse moins lourd quand on le reconnaît.",
    "Le premier pas est souvent le plus difficile. Et le plus important.",
    "La vie est faite de cycles. Les bas préparent les hauts.",
    "Chaque choix en appelle un autre. Vous n'êtes pas coincé.",
    "La bienveillance envers soi n'est pas de l'égoïsme. C'est du respect.",
    "Le lâcher-prise n'est pas renoncer. C'est faire de la place.",
    "La parole peut blesser ou guérir. Choisissez.",
    "On mérite d'être aimé tel qu'on est. Pas tel qu'on devrait être.",
    "La patience est une forme d'amour. Envers soi. Envers le temps.",
    "Le corps sait. Écoutez-le. Repos. Mouvement. Respiration.",
    "La solitude choisie régénère. La subie peut se transformer. Les deux peuvent coexister.",
    "Chaque petit progrès compte. Les invisibles aussi.",
    "La lumière existe même dans l'ombre. Elle est juste plus discrète.",
    "Le respect de soi attire le respect des autres. Commencez par vous.",
    "La vie ne nous doit rien. Nous pouvons lui prendre des moments de joie.",
    "On n'a pas à tout comprendre pour avancer. Comprendre vient parfois après.",
    // ——— Citations (Confucius, Gandhi, philosophes…) ———
    "« Le plus grand bien que je souhaite, c'est de me contenter de moi-même. » — Montaigne",
    "« Ce n'est pas parce que les choses sont difficiles que nous n'osons pas. » — Sénèque",
    "« La vie est courte. Réveillez-vous. » — Bouddha (attribué)",
    "« La seule façon de faire du bon travail est d'aimer ce que vous faites. » — Steve Jobs",
    "« Après la pluie vient le beau temps. »",
    "« Un voyage de mille lieues commence toujours par un premier pas. » — Lao Tseu",
    "« Soyez le changement que vous voulez voir dans le monde. » — Gandhi",
    "« La simplicité est la clé de la vraie élégance. » — Coco Chanel",
    "« Il n'y a qu'un bonheur : aimer et être aimé. » — George Sand",
    "« L'avenir appartient à ceux qui croient à la beauté de leurs rêves. » — Eleanor Roosevelt",
    "« La seule limite est celle que nous nous imposons. »",
    "« Chaque jour est une nouvelle chance. »",
    "« Le bonheur n'attend pas le nombre des années. »",
    "« Faites de votre vie un rêve, et d'un rêve une réalité. » — Saint-Exupéry (inspiré)",
    "« La joie est en tout ; il faut savoir l'extraire. » — Confucius (attribué)",
    "« Ce qui ne nous tue pas nous rend plus forts. » — Nietzsche",
    "« La gratitude est la mémoire du cœur. »",
    "« Le courage est de chercher la vérité, pas de croire l'avoir trouvée. »",
    "« La paix commence par un sourire. » — Mère Teresa",
    "« Vivre, c'est progresser. »",
    "« Le bonheur est contagieux. Contagiez. »",
    "« La bienveillance est la plus belle forme d'intelligence. »",
    "« Chaque instant peut être un nouveau départ. »",
    "« La sagesse est de savoir s'émerveiller. »",
    "« L'espoir est le pilier du monde. »",
    "« Rien n'est permanent, sauf le changement. » — Héraclite",
    "« La clarté vient de l'action. »",
    "« Le présent est le seul moment réel. »",
    "« Aimer, c'est voir l'autre tel qu'il est, et l'accepter. » — Goethe (inspiré)",
    // ——— Confucius ———
    "« La vraie connaissance est de connaître l'étendue de son ignorance. » — Confucius",
    "« Oublie les injures, n'oublie jamais les bienfaits. » — Confucius",
    "« Celui qui ne progresse pas chaque jour recule chaque jour. » — Confucius",
    "« Le silence est un ami qui ne trahit jamais. » — Confucius",
    "« Le sage a honte de ses défauts, mais n'a pas honte de s'en corriger. » — Confucius",
    "« Choisir un moment, c'est gagner du temps. » — Confucius (attribué)",
    "« Quand on sait, on sait ; quand on ne sait pas, on ne sait pas : c'est savoir. » — Confucius (attribué)",
    "« La nature fait les hommes semblables ; la vie les rend différents. » — Confucius",
    "« Celui qui aime à apprendre est bien près du savoir. » — Confucius",
    "« N'agissez jamais en hâte ; tenez compte du résultat final. » — Confucius",
    "« Être humain, c'est aimer les hommes. Être sage, c'est les connaître. » — Confucius",
    "« La joie est en tout ; il faut savoir l'extraire. » — Confucius (attribué)",
    "« Celui qui sait obéir saura ensuite commander. » — Confucius",
    "« La vraie faute est celle qu'on ne corrige pas. » — Confucius",
    "« Une image vaut mille mots. » — Confucius (attribué)",
    // ——— Gandhi ———
    "« Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre toujours. » — Gandhi",
    "« La vie est un mystère qu'il faut vivre, et non un problème à résoudre. » — Gandhi",
    "« Tout ce que tu feras sera dérisoire, mais il est essentiel que tu le fasses. » — Gandhi",
    "« La règle d'or de la conduite est la tolérance mutuelle. » — Gandhi",
    "« Commencez par changer en vous ce que vous voulez changer autour de vous. » — Gandhi",
    "« La non-violence est le summum du courage. » — Gandhi",
    "« Comment peut-on apprendre à se connaître ? Par la méditation, jamais ; par l'action. » — Gandhi",
    "« Vis simplement pour que d'autres puissent simplement vivre. » — Gandhi",
    "« Ce que tu gagneras par la violence, une violence plus grande te la fera perdre. » — Gandhi",
    "« La vieille philosophie de l'œil pour l'œil n'a fait que des aveugles. » — Gandhi",
    "« Ma vie est mon seul enseignement. » — Gandhi",
    "« La paix n'est pas l'absence de conflit, c'est la capacité de le gérer. » — Gandhi (attribué)",
    // ——— Lao Tseu ———
    "« Un voyage de mille lieues commence toujours par un premier pas. » — Lao Tseu",
    "« Celui qui sait ne parle pas ; celui qui parle ne sait pas. » — Lao Tseu",
    "« La nature ne se dépêche pas, pourtant tout est accompli. » — Lao Tseu",
    "« Connaître les autres, c'est sagesse ; se connaître soi-même, c'est sagesse supérieure. » — Lao Tseu",
    "« L'eau est douce et docile, mais elle use la pierre. » — Lao Tseu",
    "« Le sage ne s'accumule pas. Plus il agit pour les autres, plus il possède. » — Lao Tseu",
    "« Rien n'est plus souple que l'eau, pourtant elle use le dur. » — Lao Tseu",
    "« Celui qui se contente de ce qu'il a est toujours riche. » — Lao Tseu",
    "« La simplicité est la clé de la vraie force. » — Lao Tseu (attribué)",
    // ——— Sénèque ———
    "« Ce n'est pas parce que les choses sont difficiles que nous n'osons pas ; c'est parce que nous n'osons pas qu'elles sont difficiles. » — Sénèque",
    "« La vie est une pièce de théâtre : ce qui compte, c'est qu'elle soit bien jouée. » — Sénèque",
    "« Celui qui cherche la sagesse est un sage ; celui qui croit l'avoir trouvée est un fou. » — Sénèque",
    "« Si tu veux être aimé, aime. » — Sénèque",
    "« Le langage de la vérité est simple. » — Sénèque",
    "« Nous souffrons plus souvent en imagination qu'en réalité. » — Sénèque",
    "« Ce n'est pas que nous avons peu de temps, c'est que nous en perdons beaucoup. » — Sénèque",
    "« La chance est ce qui arrive quand la préparation rencontre l'opportunité. » — Sénèque (attribué)",
    "« Se régler sur la nature, voilà la sagesse. » — Sénèque",
    "« Il n'y a pas de vent favorable pour celui qui ne sait où il va. » — Sénèque",
    // ——— Marc Aurèle ———
    "« Au-dedans de toi est la source du bien ; elle peut toujours jaillir si tu creuses. » — Marc Aurèle",
    "« Telles que sont tes pensées, telle sera ton intelligence. » — Marc Aurèle",
    "« Personne ne se lasse d'être aidé. L'aide est conforme à la nature. » — Marc Aurèle",
    "« Souviens-toi : chacun ne vit que dans le moment présent. » — Marc Aurèle",
    "« Tu as pouvoir sur ton esprit, pas sur les événements. Réalise cela et tu trouveras la force. » — Marc Aurèle",
    "« La meilleure revanche est de ne pas ressembler à celui qui t'a blessé. » — Marc Aurèle",
    "« Accepte ce qui t'échappe et prends soin de ce qui t'est donné. » — Marc Aurèle",
    "« L'âme se teint de la couleur de tes pensées. » — Marc Aurèle",
    // ——— Bouddha (attribué) ———
    "« La paix vient de l'intérieur. Ne la cherchez pas à l'extérieur. » — Bouddha (attribué)",
    "« Mille chandelles peuvent être allumées à une seule chandelle. » — Bouddha (attribué)",
    "« Nous sommes ce que nous pensons. Tout ce que nous sommes naît de nos pensées. » — Bouddha (attribué)",
    "« La vie est courte. Réveillez-vous. » — Bouddha (attribué)",
    "« Le bonheur ne dépend pas de ce qu'on a, mais de ce qu'on est. » — Bouddha (attribué)",
    "« Ne cherchez pas le passé ; ne rêvez pas du futur. Concentrez l'esprit sur le moment présent. » — Bouddha (attribué)",
    // ——— Autres philosophes et sages ———
    "« Rien n'est permanent, sauf le changement. » — Héraclite",
    "« Connais-toi toi-même. » — Socrate (attribué)",
    "« Ce qui ne nous tue pas nous rend plus forts. » — Nietzsche",
    "« L'avenir appartient à ceux qui croient à la beauté de leurs rêves. » — Eleanor Roosevelt",
    "« La seule limite est celle que nous nous imposons. »",
    "« La paix commence par un sourire. » — Mère Teresa",
    "« La simplicité est la sophistication suprême. » — Léonard de Vinci (attribué)",
    "« Il n'y a qu'un bonheur : aimer et être aimé. » — George Sand",
    "« La seule façon de faire du bon travail est d'aimer ce que vous faites. » — Steve Jobs",
    "« Après la pluie vient le beau temps. »",
    "« Chaque jour est une nouvelle chance. »",
    "« La gratitude est la mémoire du cœur. »",
    "« Le courage est de chercher la vérité, pas de croire l'avoir trouvée. »",
    "« Vivre, c'est progresser. »",
    "« La bienveillance est la plus belle forme d'intelligence. »",
    "« Chaque instant peut être un nouveau départ. »",
    "« L'espoir est le pilier du monde. »",
    "« La clarté vient de l'action. »",
    "« Le présent est le seul moment réel. »",
    "« Faites de votre vie un rêve, et d'un rêve une réalité. » — Saint-Exupéry (inspiré)",
    "« La simplicité est la clé de la vraie élégance. » — Coco Chanel",
    "« La joie est en tout ; il faut savoir l'extraire. » — Confucius (attribué)",
    "« Le bonheur est contagieux. Contagiez. »",
    "« La sagesse est de savoir s'émerveiller. »",
    "« Épictète : Ce qui trouble les hommes ce ne sont pas les choses, mais les jugements qu'ils portent sur les choses. »",
    "« Pascal : Le cœur a ses raisons que la raison ne connaît point. »",
    "« Montaigne : Le plus grand bien que je souhaite, c'est de me contenter de moi-même. »",
    // ——— Fortunes classiques (prédiction + numéros porte-bonheur, style anglais) ———
    "Vous trouverez le bonheur en amour. Numéros porte-bonheur : 88 42 95 08 33 26 58",
    "Une bonne nouvelle arrive bientôt. Numéros porte-bonheur : 17 63 29 91 44 07 55",
    "Votre persévérance sera récompensée. Numéros porte-bonheur : 23 76 11 89 52 34 68",
    "Un voyage agréable vous attend. Numéros porte-bonheur : 05 38 72 19 84 46 21",
    "La chance sourit à vos projets. Numéros porte-bonheur : 93 27 61 14 50 88 39",
    "Une rencontre importante est en chemin. Numéros porte-bonheur : 66 12 48 95 31 77 03",
    "Votre créativité sera reconnue. Numéros porte-bonheur : 42 18 59 86 24 70 15",
    "Le succès accompagne vos efforts. Numéros porte-bonheur : 09 54 82 37 61 28 73",
    "L'harmonie règnera dans votre foyer. Numéros porte-bonheur : 16 49 25 90 53 67 11",
    "Une opportunité financière se présente. Numéros porte-bonheur : 78 32 95 06 41 69 22",
    "Votre intuition vous guidera vers le bon choix. Numéros porte-bonheur : 35 81 47 13 92 58 04",
    "L'amitié vous apportera une joie inattendue. Numéros porte-bonheur : 62 19 85 40 76 28 51",
    "Un défi se transformera en victoire. Numéros porte-bonheur : 44 97 21 68 33 55 09",
    "La sagesse viendra d'une conversation. Numéros porte-bonheur : 71 26 93 18 64 37 80",
    "Votre charme ouvrira des portes. Numéros porte-bonheur : 52 08 74 29 86 41 15",
    "Une réconciliation apportera la paix. Numéros porte-bonheur : 39 65 12 78 24 90 57",
    "Le travail bien fait sera remarqué. Numéros porte-bonheur : 17 83 46 91 35 60 22",
    "Un ancien rêve pourrait se réaliser. Numéros porte-bonheur : 58 14 72 39 85 21 67",
    "La santé et la vitalité sont avec vous. Numéros porte-bonheur : 03 47 96 30 69 12 84",
    "Une lettre ou un message vous fera plaisir. Numéros porte-bonheur : 25 71 48 93 16 52 79",
    "Vous inspirerez quelqu'un sans le savoir. Numéros porte-bonheur : 64 20 87 45 31 98 06",
    "La générosité reviendra vers vous. Numéros porte-bonheur : 36 82 19 54 77 23 90",
    "Un changement positif est en cours. Numéros porte-bonheur : 11 59 34 88 62 07 45",
    "Votre sens de l'humour séduira. Numéros porte-bonheur : 28 73 96 41 15 69 52",
    "La patience apportera une belle récompense. Numéros porte-bonheur : 50 84 17 63 29 71 38",
    // ——— Mini-leçons de chinois (drôles : caractères + onomatopées) ———
    "Apprenez le chinois : Je suis énervé = 我生气了！(wǒ shēng qì le) Grrr! Pfff! Argh! 😤",
    "Apprenez le chinois : Je suis content = 我很高兴！(wǒ hěn gāo xìng) Yippee! 🎉 *danse*",
    "Apprenez le chinois : Merci = 谢谢！(xiè xie) *sourire* *inclinaison respectueuse*",
    "Apprenez le chinois : J'ai faim = 我饿了！(wǒ è le) Groumf. *ventre qui gargouille*",
    "Apprenez le chinois : C'est délicieux = 好吃！(hǎo chī) Miam miam! *croque*",
    "Apprenez le chinois : Je veux un biscuit = 我要饼干！(wǒ yào bǐng gān) *regard insistant*",
    "Apprenez le chinois : Bonne nuit = 晚安！(wǎn ān) Zzz... *bâille* *oreiller*",
    "Apprenez le chinois : Au secours = 救命！(jiù mìng) Aaaah! *court très vite*",
    "Apprenez le chinois : Pas de souci = 没问题！(méi wèn tí) Pfiou. *détendu*",
    "Apprenez le chinois : Je suis fatigué = 我累了！(wǒ lèi le) *bâille* Zzz. Café. Encore du café.",
    "Apprenez le chinois : Bravo = 太棒了！(tài bàng le) *applaudit* Ouah!",
    "Apprenez le chinois : Je ne comprends pas = 我不懂！(wǒ bù dǒng) *tête qui fait « quoi ? »*",
    "Apprenez le chinois : J'adore = 我喜欢！(wǒ xǐ huan) *cœur dans les yeux*",
    "Apprenez le chinois : Où sont les toilettes ? = 厕所在哪里？(cè suǒ zài nǎ lǐ) *urgent*",
    "Apprenez le chinois : Je suis perdu = 我迷路了！(wǒ mí lù le) *regarde la carte à l'envers*",
    "Apprenez le chinois : C'est trop bon = 太好吃了！(tài hǎo chī le) Miam! *prend un deuxième biscuit*",
    "Apprenez le chinois : Je rigole = 我开玩笑！(wǒ kāi wán xiào) *clin d'œil* Haha!",
    "Apprenez le chinois : Je suis surpris = 我惊呆了！(wǒ jīng dāi le) O.O *bouche ouverte*",
    "Apprenez le chinois : D'accord = 好的！(hǎo de) *hoche la tête* Ok, ok.",
    "Apprenez le chinois : À votre santé = 干杯！(gān bēi) *trinque* Cling!",
    // ——— Drôle mais léger (sourire, pas lourd) ———
    "La vie est un biscuit. Croquez.",
    "Vous avez déjà réussi quelque chose aujourd'hui : vous avez ouvert ce biscuit.",
    "Ce message ne changera pas votre vie. Mais il peut changer votre minute.",
    "La prochaine personne qui vous demandera l'heure aura une montre. C'est de la logique.",
    "Une opportunité se cache derrière un détail. Ce détail ? Peut-être ce biscuit.",
    "Le destin est capricieux. Ce biscuit, lui, est délicieux.",
    "Quelqu'un pense à vous. C'est peut-être vous, en vous relisant.",
    "Une porte va s'ouvrir. Poussez. Si c'est le placard, refermez.",
    "Vous allez bientôt avoir envie d'un autre biscuit. C'est normal.",
    "La sagesse est dans les biscuits. Enfin, dans celui-ci. Vous venez de le croquer.",
    "Le prochain café sera bon. Ou le thé. Ou ce biscuit. Au moins un des trois.",
    "Une bonne nouvelle arrive. Elle est peut-être dans cette phrase. En tout cas, vous l'avez lue.",
    "Votre intuition a raison. Sauf quand elle a tort. Là, elle a raison.",
    "Un détail va tout changer. Ce n'est peut-être pas ce détail. Mais un détail.",
    "Vous allez faire rire quelqu'un. Peut-être en lui montrant ce message.",
    "La chance sourit aux audacieux. Et aux gens qui ouvrent des biscuits.",
    "Un petit miracle du quotidien vous attend. Vous venez peut-être de le vivre.",
    "Quelqu'un va vous offrir un biscuit. Vous en tenez un. Coïncidence ?",
    "Le prochain obstacle sera plus petit qu'il n'y paraît. Comme ce message. Petit mais costaud.",
    "Une lumière au bout du tunnel ? C'est peut-être la fenêtre du voisin. Ou la vôtre.",
    "Vous êtes en train de lire un message qui vous fera du bien. Vous y êtes.",
    "Votre prochaine erreur sera sans conséquence. Ou alors si. En tout cas, ce message ne juge pas.",
    "Un mot gentil va vous être adressé. « Merci. » « Tu assures. » Ou : « Ce biscuit était bon. »",
    "La prochaine chose que vous lirez vous fera du bien. Attendez — vous lisez déjà. Parfait.",
    "Vous allez découvrir quelque chose de délicieux. Vous venez de le faire. Bravo.",
    "Un petit geste aura de grandes conséquences. Ce biscuit en est un. Vous en êtes un autre.",
    "Votre prochaine pause sera productive. Ou pas. En tout cas, prenez-la.",
    "Une idée lumineuse va vous tomber dessus. Protégez-vous. Ou accueillez-la.",
    "Vous allez croiser un animal qui vous fera sourire. Un chien. Un chat. Ou le souvenir de ce biscuit.",
    "Quelqu'un va vous remercier. Si ce n'est pas pour le biscuit, ce sera pour autre chose.",
    "Le hasard va vous faire un clin d'œil. Si vous ne le voyez pas, c'est qu'il cligne de l'autre œil.",
    "Votre sens de l'humour va sauver une situation. Gardez ce biscuit en réserve.",
    "Une porte va s'entrouvrir. Entrez. Si c'est la salle de bain, frappez.",
    "Votre bonne humeur va être contagieuse. Contagiez. Dans le bon sens du terme.",
    "Le prochain problème aura une solution simple. Parfois la solution, c'est un biscuit. Et une respiration.",
    "Vous allez recevoir un compliment. Il pourrait venir de ce biscuit : « Tu as bien choisi. »",
    "Un détail va vous apaiser. Ce détail. Cette phrase. Ce moment.",
    "Vous allez réussir quelque chose que vous aviez reporté. Aujourd'hui. Ou demain. Mais vous allez réussir.",
    "La chance tourne. Elle passe par vous. Elle a peut-être un ticket. Ou un biscuit.",
    "Un petit plaisir va vous faire oublier un petit souci. Ce biscuit. Cette phrase. Vous.",
    "Quelqu'un va vous faire confiance. Ne les décevez pas. (Vous ne les décevrez pas.)",
    "Vous allez croiser quelqu'un qui vous fait du bien. Peut-être vous-même. En étant gentil avec vous.",
    "Une rencontre fortuite va vous inspirer. Un inconnu. Un ami. Un biscuit.",
    "La prochaine fois que vous hésiterez, la bonne option sera un peu plus évidente. Ou pas. En tout cas, respirez.",
    "Vous allez aider quelqu'un sans vous en rendre compte. C'est souvent comme ça.",
    "Un objet perdu va réapparaître. Les clés. Le stylo. La sérénité. Un des trois.",
    "Une bonne nouvelle va arriver par la petite porte. Ou par notification. Ou par biscuit.",
    "Vous allez faire la différence pour quelqu'un. Sans le savoir. Merci à vous.",
    "Une surprise positive est en route. Elle pourrait être ce biscuit. Ou la vie. Les deux.",
    "Le hasard va vous donner un coup de pouce. Ou un biscuit. Les deux sont bons.",
    "Votre prochaine pause sera bien méritée. Prenez-la. Sans culpabilité.",
    "Vous allez réussir à faire quelque chose que vous redoutiez. Petit ou grand. Vous allez réussir.",
    "Un détail va vous faire réaliser que tout va un peu mieux. Ce détail. Cette phrase. Ce moment.",
    "Quelqu'un pense à vous et vous enverra un signe. Un message. Un biscuit. Un sourire.",
    "Une idée va vous venir en faisant tout autre chose. En marchant. En dormant. En lisant ce biscuit.",
    "Vous allez recevoir une aide inattendue. D'un ami. D'un inconnu. Ou d'un biscuit.",
    "Le prochain obstacle sera une opportunité déguisée. Ouvrez l'œil. Ou le biscuit.",
    "Un petit geste va déclencher une chaîne de bons moments. Votre geste. Ce biscuit. La suite.",
    "Quelqu'un va vous dire que vous comptez. C'est vrai. Même si personne ne vous l'a dit aujourd'hui.",
    "Une lumière va s'allumer. Au sens propre. Ou dans votre tête. Les deux si vous voulez.",
    "Vous allez trouver exactement ce que vous cherchiez. Ou mieux. Un biscuit. Une phrase. Une raison de sourire.",
    "Votre patience va payer. Aujourd'hui. Ou demain. En tout cas, elle paie. Ce biscuit en est la preuve.",
    "Un message va vous rassurer. Celui-ci. Ou le prochain. Ou votre propre voix. Écoutez.",
    "Votre curiosité va être récompensée. Vous avez ouvert le biscuit. Vous avez lu. Récompense.",
    "Vous allez faire sourire quelqu'un. Mission du jour. Avec un mot. Ce biscuit. Un geste.",
    "Le prochain obstacle sera franchi. Par vous. Ce biscuit est avec vous.",
    "Votre optimisme va payer. Encore une fois. Ce biscuit mise sur vous.",
    "Un petit bonheur va se glisser dans votre journée. Déjà là. Ou en chemin. Ouvrez l'œil.",
    "Quelqu'un va vous faire rire. Profitez. C'est bon pour tout.",
    "Votre prochaine action va compter. Faites-la. Même petite. Elle compte.",
    "Une bonne nouvelle va arriver. Tenez-vous prêt. Vous l'êtes. Déjà.",
    "Vous allez recevoir un signe. Positif. Ouvrez les yeux. Ce signe. Ce biscuit. Ce moment.",
    "Le prochain compliment sera mérité. Acceptez-le. Vous le méritez.",
    "Votre créativité va briller. Montrez-la. Dans un message. Un projet. Un biscuit partagé.",
    "Un petit miracle du quotidien. Aujourd'hui. Ici. Maintenant. Ou tout à l'heure. Ce biscuit. Ce moment.",
    "Quelqu'un va vous faire confiance. Vous le méritez. Ce biscuit vous fait confiance. Montrez-le.",
    "Votre prochaine bonne action sera remarquée. Ou pas. Elle comptera. Faites-la.",
    "Une opportunité se cache. Derrière un détail. Derrière une porte. Ou derrière ce biscuit. Ouvrez. Cherchez.",
    "Vous allez recevoir une preuve que vous comptez. Ce biscuit. Ce message. Cette preuve.",
    "Le prochain message vous fera du bien. Ouvrez. Lisez. Souriez. Celui-ci. Le prochain. Les deux.",
    "Votre intuition aujourd'hui : fiable. Écoutez-la. Elle a raison.",
    "Un détail va vous prouver que vous êtes sur la bonne voie. Ce détail. Cette phrase. Ce biscuit.",
    "Votre prochaine idée sera la bonne. Au bon moment. Notez. Faites.",
    "Une bonne nouvelle va arriver. Bientôt. Très bientôt. Ou c'est déjà celle-ci. Restez à l'écoute.",
    "Vous allez réussir. À quelque chose. Aujourd'hui. Petit ou grand. Les deux comptent.",
    "Le prochain défi sera relevé. Par vous. Ce biscuit croit en vous.",
    "Votre optimisme va faire la différence. Pour vous. Pour quelqu'un. Pour la journée.",
    "Un petit geste va déclencher une vague de positivité. Votre geste. Ce biscuit. Cette vague.",
    "Quelqu'un va vous remercier. Et ça va vous faire du bien. Acceptez. Souriez.",
    "Votre prochaine pause sera l'occasion d'une bonne idée. D'un souffle. Prenez-la.",
    "Une porte va s'ouvrir. Entrez. Vous êtes attendu. Ou pas. Entrez quand même.",
    "Vous allez croiser la chance. Ou elle va vous croiser. Même combat. Bonne journée.",
    // ——— Encore un peu de variété (léger + identifiant) ———
    "Le prochain SMS que vous enverrez sera apprécié. Envoyez-le.",
    "Une personne va vous dire merci aujourd'hui. Ou demain. En tout cas, vous comptez.",
    "Votre prochaine bonne idée est en train de mûrir. Laissez-la venir.",
    "Un rayon de soleil va croiser votre route. Littéralement ou pas. Ouvrez l'œil.",
    "Vous allez entendre une chanson qui vous fera du bien. Ou vous l'avez déjà entendue. Les deux comptent.",
    "Quelqu'un va vous sourire. Souriez en retour. C'est contagieux.",
    "Votre prochaine nuit sera meilleure que la précédente. Ou au moins différente. Reposez-vous.",
    "Un détail va vous faire penser à quelqu'un que vous aimez. Pensez à lui. À elle. C'est bon.",
    "Vous allez réussir à vous détendre. Au moins cinq minutes. C'est déjà ça.",
    "La prochaine fois que vous vous demanderez « à quoi bon », rappelez-vous : à beaucoup. Ce biscuit par exemple.",
    "Un souvenir agréable va remonter. Accueillez-le. Il fait partie de vous.",
    "Vous allez faire un choix qui vous ressemble. Faites-vous confiance.",
    "Quelqu'un va vous demander votre avis. Donnez-le. Il compte.",
    "Votre prochaine inspiration peut venir de n'importe où. D'un livre. D'une marche. D'un biscuit.",
    "Une bonne nouvelle va arriver. Par la voix. Par l'écran. Par la vie. Restez à l'écoute.",
    "Vous allez vous sentir un peu plus léger. Ou un peu plus en paix. Ou les deux. Soufflez.",
    "Le prochain compliment que vous recevrez sera sincère. Acceptez-le. Vous le méritez.",
    "Un petit pas va vous rapprocher de quelque chose d'important. Faites-le.",
    "Quelqu'un va vous faire confiance. Vous ne les décevrez pas. Vous en êtes capable.",
    "Votre prochaine conversation sera utile. À vous. À l'autre. Ou aux deux. Engagez-la.",
    "Une opportunité va se présenter. Elle pourrait être discrète. Ouvrez l'œil.",
    "Vous allez trouver la force de faire ce que vous repoussiez. La force est en vous.",
    "Le prochain obstacle sera plus petit que vous ne le pensiez. Vous allez le franchir.",
    "Un message va vous faire chaud au cœur. Celui-ci. Ou le prochain. Ou les deux.",
    "Quelqu'un va vous remercier pour votre présence. Votre présence compte.",
    "Votre prochaine pause sera réparatrice. Prenez-la. Sans culpabilité.",
    "Une lumière va s'allumer. Dans votre tête. Dans la pièce. Dans votre journée. Lumière.",
    "Vous allez recevoir une preuve que les choses avancent. Ce biscuit. Un regard. Un mot. Vous.",
    "Le prochain « oui » que vous direz sera le bon. Pour vous. Pour les autres. Oui.",
    "Votre créativité va s'exprimer. Dans un message. Un projet. Un geste. Laissez-la faire.",
    "Un petit miracle du quotidien. Aujourd'hui. Ici. Ou tout à l'heure. Ce biscuit. Ce moment.",
    "Quelqu'un pense à vous. Et vous comptez. Ce biscuit vous le rappelle.",
    "Votre prochaine bonne action sera remarquée. Ou pas. Elle comptera. Faites-la quand même.",
    "Une bonne nouvelle va arriver. Bientôt. Très bientôt. Ou c'est déjà celle-ci. Restez ouverts.",
    "Vous allez faire sourire quelqu'un. Mission du jour. Avec un mot. Un geste. Ce biscuit. Vous.",
    "Le prochain défi sera à votre portée. Relevez-le. Ce biscuit est avec vous.",
    "Votre intuition aujourd'hui : fiable. Écoutez-la. Elle a souvent raison.",
    "Un détail va vous rassurer. Sur la suite. Sur vous. Ce détail. Cette phrase. Ce moment.",
    "Quelqu'un va vous dire que vous comptez. C'est vrai. Même si vous ne le voyez pas toujours.",
    "Votre prochaine réussite est proche. Continuez. Vous y êtes presque. Ou vous y êtes déjà.",
    "Une porte va s'ouvrir. Poussez. Entrez. Vous êtes attendu. Ou pas. Entrez.",
    "Vous allez trouver ce qu'il vous faut. Ou mieux. Un biscuit. Une phrase. Une raison de croire.",
    "Le prochain message vous fera du bien. Ouvrez. Lisez. Souriez. Celui-ci. Le prochain.",
    "Votre optimisme va payer. Encore une fois. Ce biscuit mise sur vous. Nous aussi.",
    "Un petit bonheur va se glisser dans votre journée. Déjà là. Ou en chemin. Ouvrez l'œil.",
    "Quelqu'un va vous faire rire. Profitez. C'est bon pour la santé. Pour la vôtre.",
    "Votre prochaine action va compter. Faites-la. Même petite. Même invisible. Elle compte.",
    "Une opportunité se cache. Quelque part. Aujourd'hui. Dans une conversation. Dans ce biscuit. Cherchez.",
    "Vous allez recevoir un encouragement. Vous en avez besoin. Vous le méritez. Le voici.",
    "Le prochain problème aura une solution. Vous la trouverez. Ou elle vous trouvera. En tout cas : solution.",
    "Votre bonne humeur va être remarquée. En bien. Contagiez. Dans le bon sens.",
    "Un détail va vous faire du bien. Trouvez-le. Ce détail. Cette phrase. Ce biscuit. Vous.",
    "Quelqu'un va vous remercier. Et ça va vous faire du bien. Acceptez. Souriez. Merci.",
    "Votre prochaine idée sera bonne. Notez-la. Faites-la. Ce biscuit vous encourage.",
    "Une bonne nouvelle va arriver. Par un canal inattendu. Un message. Un biscuit. Un regard. Restez à l'écoute.",
    "Vous allez réussir. À quelque chose. Aujourd'hui. Petit ou grand. Les deux comptent. Ce biscuit y croit.",
    "Le prochain compliment sera mérité. Acceptez-le. Vous le méritez. Ce biscuit le sait.",
    "Votre humour va sauver la journée. La vôtre. Celle d'un autre. Ou les deux. Utilisez-le.",
    "Un petit geste va tout changer. Le vôtre. Celui d'un autre. Faites. Recevez. Les deux.",
    "Quelqu'un va vous faire confiance. Vous le méritez. Ce biscuit vous fait confiance. Montrez-le.",
    "Votre prochaine pause sera l'occasion d'une bonne idée. D'un souffle. Prenez-la. Sans culpabilité.",
    "Une lumière va jaillir. En vous. Ou autour. Les deux. Pourquoi pas. Ce biscuit allume. Vous aussi.",
    "Vous allez croiser quelqu'un de bien. Souriez. Ça aide. Ce biscuit sourit avec vous.",
    "Le prochain message sera positif. Ouvrez-le. Lisez-le. Partagez-le. Comme ce biscuit.",
    "Votre intuition a raison. Encore. Écoutez-la. Sauf pour les biscuits. Là, ouvrez. Toujours.",
    "Un détail va vous prouver que vous êtes sur la bonne voie. Ce détail. Cette phrase. Ce biscuit.",
    "Quelqu'un va vous faire du bien. Sans le savoir. Ou en le sachant. Acceptez. Et faites de même.",
    "Votre prochaine bonne action comptera. Faites-la. Ce biscuit compte. Vous comptez.",
    "Une opportunité va se présenter. Soyez prêt. Vous l'êtes. Ce biscuit aussi. Allez.",
    "Vous allez recevoir un signe. Positif. Ouvrez les yeux. Ce signe. Ce biscuit. Ce moment.",
    "Le prochain « non » ne sera pas grave. Promis. Ou alors si. Mais vous vous en remettrez. Ce biscuit vous le promet.",
    "Votre créativité va briller. Montrez-la. Dans un message. Un projet. Un biscuit partagé. Partout.",
    "Un petit miracle du quotidien. Aujourd'hui. Ici. Maintenant. Ou tout à l'heure. Ce biscuit. Vous. Miracle.",
    "Quelqu'un pense à vous. Et c'est réciproque. Vous comptez. Ce biscuit le confirme. Encore. Toujours.",
    "Votre prochaine bonne nouvelle est en route. Patience. Elle arrive. Ou c'est ce biscuit. Les deux.",
    "Une bonne nouvelle va arriver. Par la petite porte. Ou la grande. Peu importe. Elle arrive.",
    "Vous allez trouver la force. Elle est en vous. Depuis toujours. Ce biscuit le rappelle.",
    "Le prochain obstacle sera franchi. Par vous. Sans problème. Ce biscuit est avec vous. Allez.",
    "Votre sourire va tout changer. Pour quelqu'un. Pour vous. Pour la journée. Changez. Souriez.",
    "Un détail va vous inspirer. Ouvrez les yeux. Les oreilles. Le cœur. Ce détail. Ce biscuit. Inspirez.",
    "Quelqu'un va vous faire un compliment. Sincère. Mérité. Acceptez. Ce biscuit vous en fait un : vous avez bien fait d'ouvrir.",
    "Votre prochaine initiative sera couronnée de succès. Ou au moins appréciée. Lancez-vous. Ce biscuit vous pousse.",
    "Une lumière va s'allumer. En vous. Ou autour. Les deux. Pourquoi pas. Ce biscuit allume. Vous aussi.",
    "Vous allez faire sourire quelqu'un. Sans le savoir. Ou en le sachant. Mission accomplie.",
    "Le prochain « oui » sera le bon. Pour vous. Pour les autres. Pour tout le monde. Oui.",
    "Votre créativité va s'exprimer. Laissez-la faire. Elle est bonne. Ce biscuit l'exprime. Vous aussi.",
    "Un petit miracle : ça existe. Aujourd'hui. Par exemple. Ce biscuit. Ce moment. Vous.",
    "Quelqu'un va vous faire confiance. Vous le méritez. Montrez-le. Ce biscuit vous fait confiance. Nous aussi.",
    "Votre prochaine bonne action sera remarquée. Ou pas. Elle comptera. Faites-la. Ce biscuit compte. Vous comptez.",
    "Une opportunité se cache. Derrière un détail. Derrière une porte. Ouvrez. Cherchez. Ce biscuit. Cette phrase.",
    "Vous allez recevoir une preuve. Que vous comptez. Que ça avance. Que tout va mieux. Ce biscuit. Ce message. Vous.",
    "Le prochain message vous fera du bien. Ouvrez. Lisez. Souriez. Celui-ci. Le prochain. Les deux. Du bien.",
    "Votre intuition aujourd'hui : fiable. Écoutez-la. Elle a raison. Ce biscuit aussi. Fiable.",
    "Un détail va vous prouver que vous êtes sur la bonne voie. Cherchez. Trouvez. Ce détail. Cette phrase. Ce biscuit.",
    "Quelqu'un va vous faire rire. Profitez. C'est bon. Pour tout. Ce biscuit vous y encourage. Riez. Profitez.",
    "Votre prochaine idée sera la bonne. Au bon moment. Notez. Faites. Ce biscuit note. Vous notez. Faites.",
    "Une bonne nouvelle va arriver. Tenez-vous prêt. Vous l'êtes. Déjà. Ce biscuit aussi. Prêt. Nouvelle.",
    "Vous allez réussir. À quelque chose d'important. Ou de petit. Les deux comptent. Ce biscuit compte. Vous comptez.",
    "Le prochain défi sera relevé. Par vous. Sans stress. Ou avec. Mais relevé. Ce biscuit relève. Vous relevez.",
    "Votre optimisme va faire la différence. Pour vous. Pour quelqu'un. Pour la journée. Ce biscuit fait la différence. Vous aussi.",
    "Un petit geste va déclencher une vague. De positivité. De gratitude. De joie. Votre geste. Ce biscuit. Cette vague.",
    "Quelqu'un va vous remercier. Et ça va vous faire du bien. Acceptez. Souriez. Ce biscuit remercie. Vous remerciez.",
    "Votre prochaine pause sera l'occasion. D'une bonne idée. D'un souffle. Prenez-la. Ce biscuit vous donne l'occasion.",
    "Une porte va s'ouvrir. Entrez. Vous êtes attendu. Ou pas. Entrez quand même. Ce biscuit entre. Vous entrez.",
    "Vous allez croiser la chance. Elle va vous croiser. Même combat. Bonne journée. Ce biscuit vous la souhaite. Nous aussi.",
  ];

  /// Tire une fortune au hasard.
  static String drawFortune() {
    return _fortunes[_random.nextInt(_fortunes.length)];
  }
}
